public class ArtGalleryManagementSystem {
    public static void main(String[] args) {
        Painting theKiss = new Painting();
        theKiss.displayDetails("The kiss", "Gustav Klimt", "  gustav Klimt's  painting     'The Kiss' portrays a couple's intimate embrace, wrapped in golden patterns and symbolic motifs, embodying love and passion. dimensions: 1,8 m x 1,8 m.  ");
        theKiss.addCritique("Gustav Klimt depicts the couple locked in an intimate embrace against a gold, flat background. The two figures are situated at the edge of a patch of flowery meadow that ends under the woman's exposed feet. The man wears a robe printed with geometric patterns and subtle swirls. He wears a crown of vines while the woman wears a crown of flowers. She is shown in a flowing dress with floral patterns. The man's face is not shown to the audience and instead, his face is bent downward to press a kiss to the woman's cheek, and his hands are cradling the woman's face. Her eyes are closed, with one arm wrapped around the man's neck, the other resting gently on his hand, and her face is upturned to receive the man's kiss.\n" +
                "\n" +
                "The patterns in the painting suggests the style of Art Nouveau and the organic forms of the Arts and Crafts movement. At the same time, the background evokes the conflict between two- and three-dimensionality intrinsic to the work of Degas and other modernists. Paintings such as The Kiss are visual manifestations of fin-de-siecle spirit because they capture a decadence conveyed by opulent and sensuous images. The use of gold leaf recalls medieval gold-ground paintings, illuminated manuscripts, earlier mosaics, and the spiral patterns in the clothes recall Bronze Age art and the decorative tendrils seen in Western art since before classical times. The man's head ends very close to the top of the canvas, a departure from traditional Western canons that reflects the influence of Japanese prints, as does the painting's simplified composition.");
    }
}
